ADD_APPEAL_PERMISSION = "appeals.add_appeal"
CHANGE_APPEAL_PERMISSION = "appeals.change_appeal"
VIEW_APPEAL_PERMISSION = "appeals.view_appeal"
START_APPEAL_PROCESSING_PERMISSION = "appeals.start_appeal_processing"
COMMENT_APPEAL_PERMISSION = "appeals.comment_appeal"
CLOSE_APPEAL_PERMISSION = "appeals.close_appeal"
TRANSFER_APPEAL_PERMISSION = "appeals.transfer_appeal"

START_APPEAL_PROCESSING_CODENAME = "start_appeal_processing"
COMMENT_APPEAL_CODENAME = "comment_appeal"
CLOSE_APPEAL_CODENAME = "close_appeal"
TRANSFER_APPEAL_CODENAME = "transfer_appeal"

OPERATOR_PERMISSIONS = [
    ADD_APPEAL_PERMISSION,
    VIEW_APPEAL_PERMISSION,
    COMMENT_APPEAL_PERMISSION,
    CLOSE_APPEAL_PERMISSION,
]

RESPONSIBLE_PERMISSIONS = [
    VIEW_APPEAL_PERMISSION,
    START_APPEAL_PROCESSING_PERMISSION,
    COMMENT_APPEAL_PERMISSION,
    CLOSE_APPEAL_PERMISSION,
    TRANSFER_APPEAL_PERMISSION,
]
